site_name: Nucleus
nav:
  - Introduction: index.md
  - Mission Concepts: concepts.md
  - Concept Selection: concept-selection.md
  - Mission Profile: mission-profile.md
  - Preliminary Design: pdr.md
  - Glossary: glossary.md
  - Contribute: contribute.md

theme: readthedocs
markdown_extensions:
  - toc
  - admonition
  - footnotes
extra_javascript:
  - js/extra.js
