site_name: Nucleus
site_description: A high altitude balloon and the first mission from Brickworks.
repo_url: https://github.com/Brickworks/Nucleus
repo_name: Brickworks/Nucleus
nav:
  - Introduction: index.md
  - Mission Selection:
    - Mission Concepts: concepts.md
    - Concept Selection: concept-selection.md
  - Preliminary Design:
    - Mission Profile: mission-profile.md
    - Flight Avionics Software: pdr_avsw.md
    - Flight Avionics Hardware: pdr_avhw.md
    - Altitude Control Logic: pdr_altitudecontrol.md
  - Appendix:
    - Glossary: glossary.md
    - Contribute: contribute.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/dice-d6
  favicon: img/favicon.ico
  palette:
  - scheme: default
    primary: blue
    accent: blue

plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
