site_name: Nucleus
nav:
  - Introduction: index.md
  - Mission Selection:
    - Mission Concepts: concepts.md
    - Concept Selection: concept-selection.md
  - Preliminary Design:
    - Mission Profile: mission-profile.md
    - Flight Avionics Software: pdr_avsw.md
    - Flight Avionics Hardware: pdr_avhw.md
    - Altitude Control Logic: pdr_altitudecontrol.md
  - HAB Toolbox:
    - 1D Atmospheric Flight Model: habtoolbox_1d-ascent-model.md
  - Appendix:
    - Glossary: glossary.md
    - Contribute: contribute.md

theme: readthedocs
plugins:
  - search
markdown_extensions:
  - toc
  - admonition
  - footnotes
extra_javascript:
  - js/extra.js
