name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Deploy docs
<<<<<<< HEAD
        run: poetry run mkdocs gh-deploy --force
=======
        run: mkdocs gh-deploy --force
>>>>>>> CI: fix workflows for docs deployments
