name: Build and Deploy Docs to GitHub Pages

on:
  push:
    branches:
    - master
    - gh-pages

jobs:
  build-deploy-docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    
    - name: Build Docs with Sphinx
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install sphinx sphinx_rtd_theme"

    - name: Deploy Docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/_build/html
