name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        build-command: "sphinx-build -b html . _build"